<script setup lang="ts">
const route = useRoute()
const code = String(route.params.code)
const activeTab = ref('about')
const projectTasks = [{ key: 'MOB-142', title: 'Обновить onboarding', status: 'В работе', priority: 'Высокий', assignee: 'ИС' }, { key: 'MOB-138', title: 'Добавить push-уведомления', status: 'К выполнению', priority: 'Средний', assignee: 'МВ' }, { key: 'MOB-129', title: 'Исправить оплату картой', status: 'Заблокировано', priority: 'Критичный', assignee: 'АП' }]
const releases = [{ version: '2.4.0', status: 'В подготовке', date: '18 августа', scope: '12 задач из Jira' }, { version: '2.3.2', status: 'Выпущен', date: '04 августа', scope: '8 задач из Jira' }]
const risks = [{ title: 'Зависимость от API платежей', owner: 'Иван Соколов', impact: 'Высокий', status: 'Открыт' }, { title: 'Не готов контент для onboarding', owner: 'Анна Петрова', impact: 'Средний', status: 'На контроле' }]
const activity = [{ text: 'Иван Соколов обновил задачу MOB-142', time: '12 минут назад', source: 'Jira', icon: 'i-lucide-refresh-cw' }, { text: 'В staging опубликована версия 2.3.2', time: '2 часа назад', source: 'Автоматически', icon: 'i-lucide-rocket' }, { text: 'Добавлена заметка: проверить тексты onboarding', time: 'Вчера', source: 'CRM', icon: 'i-lucide-sticky-note' }]
const notes = [{ title: 'Проверить тексты onboarding', text: 'Нужно сверить финальные тексты перед передачей в разработку.', author: 'Анна Петрова', source: 'CRM', time: 'Вчера' }, { title: 'Обсудить лимиты API платежей', text: 'Зафиксировать ограничения и сценарий деградации.', author: 'Иван Соколов', source: 'Telegram', time: '2 дня назад' }]

const projects: Record<string, { name: string; description: string; status: string; updated: string; team: { name: string; role: string; initials: string }[]; modules: string[]; environments: { name: string; detail: string; status: string }[]; artifacts: { name: string; type: string; url: string }[] }> = {
  'MOB-24': {
    name: 'Мобильное приложение', description: 'Клиентское приложение для пользователей сервиса.', status: 'В работе', updated: 'Сегодня, 10:42',
    team: [{ name: 'Анна Петрова', role: 'Product Manager', initials: 'АП' }, { name: 'Иван Соколов', role: 'Lead Developer', initials: 'ИС' }, { name: 'Мария Волкова', role: 'UX/UI Designer', initials: 'МВ' }],
    modules: ['Авторизация', 'Профиль пользователя', 'Каталог', 'Уведомления', 'Платежи', 'Поддержка'],
    environments: [{ name: 'Production', detail: 'app.example.com', status: 'Стабильна' }, { name: 'Staging', detail: 'staging.app.example.com', status: 'Готова' }, { name: 'Development', detail: 'Локальная среда', status: 'Активна' }],
    artifacts: [{ name: 'Техническая документация', type: 'Документация', url: 'docs.example.com/mobile' }, { name: 'Макеты приложения', type: 'Figma', url: 'figma.com/file/mobile-app' }, { name: 'API контракт', type: 'OpenAPI', url: 'api.example.com/openapi' }]
  }
}

const project = computed(() => projects[code] ?? projects['MOB-24'])
const tabs = [{ value: 'about', label: 'Проект', icon: 'i-lucide-layout-dashboard' }, { value: 'modules', label: 'Модули', icon: 'i-lucide-box' }, { value: 'tasks', label: 'Задачи', icon: 'i-lucide-list-checks' }, { value: 'releases', label: 'Релизы', icon: 'i-lucide-rocket' }, { value: 'environments', label: 'Среды', icon: 'i-lucide-server' }, { value: 'artifacts', label: 'Артефакты', icon: 'i-lucide-link-2' }]
</script>

<template>
  <UDashboardPanel id="project-detail">
    <template #header>
      <UDashboardNavbar :title="project.name">
        <template #leading><UDashboardSidebarCollapse /></template>
        <template #right><UButton icon="i-lucide-more-horizontal" color="neutral" variant="ghost" square /></template>
      </UDashboardNavbar>
    </template>
    <template #body>
      <div class="flex flex-col gap-6">
        <div class="flex flex-col gap-3 border-b border-default pb-6 sm:flex-row sm:items-start sm:justify-between">
          <div><div class="flex items-center gap-2"><NuxtLink to="/" class="text-sm text-muted hover:text-highlighted">Проекты</NuxtLink><UIcon name="i-lucide-chevron-right" class="size-4 text-dimmed" /><span class="text-sm text-muted">{{ code }}</span></div><h1 class="mt-3 text-2xl font-semibold text-highlighted">{{ project.name }}</h1><p class="mt-1 max-w-2xl text-sm text-muted">{{ project.description }}</p></div>
          <UBadge color="primary" variant="subtle">{{ project.status }}</UBadge>
        </div>

        <div class="flex gap-1 overflow-x-auto border-b border-default" role="tablist" aria-label="Разделы проекта">
          <button v-for="tab in tabs" :key="tab.value" type="button" role="tab" :aria-selected="activeTab === tab.value" class="flex shrink-0 items-center gap-2 border-b-2 px-4 py-3 text-sm font-medium transition-colors" :class="activeTab === tab.value ? 'border-primary text-highlighted' : 'border-transparent text-muted hover:text-highlighted'" @click="activeTab = tab.value"><UIcon :name="tab.icon" class="size-4" />{{ tab.label }}</button>
        </div>

        <section v-if="activeTab === 'about'" class="flex flex-col gap-8" role="tabpanel">
          <div class="flex flex-wrap items-center gap-x-6 gap-y-3 rounded-lg bg-elevated/50 px-4 py-3"><div class="flex items-center gap-2"><span class="size-2 rounded-full bg-success" /><span class="text-sm text-muted">Статус</span><span class="text-sm font-medium text-highlighted">{{ project.status }}</span></div><span class="hidden text-dimmed sm:inline">·</span><div class="flex items-center gap-2 text-sm text-muted"><UIcon name="i-lucide-clock-3" class="size-4" />Обновлено {{ project.updated.toLowerCase() }}</div></div>
          <UCard variant="subtle"><div class="flex items-center justify-between gap-4"><div><h2 class="font-semibold text-highlighted">Команда проекта</h2><p class="mt-1 text-sm text-muted">Участники, доступные для назначения на модули</p></div><UButton icon="i-lucide-user-plus" label="Изменить" variant="soft" size="sm" /></div><div class="mt-5 divide-y divide-default"><div v-for="member in project.team" :key="member.name" class="flex items-center justify-between gap-4 py-3 first:pt-0 last:pb-0"><div class="flex items-center gap-3"><UAvatar :text="member.initials" size="sm" color="neutral" /><div><p class="text-sm font-medium text-highlighted">{{ member.name }}</p><p class="mt-1 text-xs text-muted">{{ member.role }}</p></div></div><UButton icon="i-lucide-more-horizontal" color="neutral" variant="ghost" square size="sm" aria-label="Действия участника" /></div></div></UCard>
          <section class="pt-1"><div class="flex items-center justify-between gap-4"><div><h2 class="font-semibold text-highlighted">Риски и стоперы</h2><p class="mt-1 text-sm text-muted">Закреплённые проблемы из активности, которые требуют контроля</p></div><UButton icon="i-lucide-plus" label="Добавить стопер" variant="soft" size="sm" /></div><div class="mt-5 divide-y divide-default"><div v-for="risk in risks" :key="risk.title" class="flex items-center justify-between gap-4 py-3 first:pt-0 last:pb-0"><div class="flex min-w-0 items-center gap-3"><span class="size-2 shrink-0 rounded-full bg-warning" /><div class="min-w-0"><p class="truncate text-sm font-medium text-highlighted">{{ risk.title }}</p><p class="mt-1 text-xs text-muted">{{ risk.owner }} · Влияние: {{ risk.impact }}</p></div></div><UBadge color="warning" variant="subtle">{{ risk.status }}</UBadge></div></div></section>
          <section class="pt-1"><div class="flex items-center justify-between gap-4"><div><h2 class="font-semibold text-highlighted">Заметки по проекту</h2><p class="mt-1 text-sm text-muted">Заметки из CRM и внешних каналов, например Telegram</p></div><div class="flex items-center gap-2"><NuxtLink to="/projects/MOB-24/notes" class="text-sm text-primary hover:underline">Все заметки</NuxtLink><UButton icon="i-lucide-sticky-note" label="Добавить" variant="soft" size="sm" /></div></div><div class="mt-5 divide-y divide-default"><NuxtLink v-for="note in notes" :key="note.title" to="/projects/MOB-24/notes" class="flex items-start justify-between gap-4 py-3 first:pt-0 last:pb-0"><div class="min-w-0"><p class="truncate text-sm font-medium text-highlighted">{{ note.title }}</p><p class="mt-1 line-clamp-1 text-sm text-muted">{{ note.text }}</p><p class="mt-2 text-xs text-dimmed">{{ note.author }} · {{ note.time }}</p></div><UBadge color="neutral" variant="subtle">{{ note.source }}</UBadge></NuxtLink></div></section>
          <section class="rounded-lg bg-elevated/30 px-4 py-5 sm:px-6"><div class="flex items-center justify-between gap-4"><div><h2 class="font-semibold text-highlighted">Последняя активность</h2><p class="mt-1 text-sm text-muted">Автоматические и ручные события проекта</p></div><UButton icon="i-lucide-plus" label="Зафиксировать событие" variant="soft" size="sm" /></div><div class="mt-5 divide-y divide-default"><div v-for="item in activity" :key="item.text" class="flex items-center gap-3 py-3 first:pt-0 last:pb-0"><span class="flex size-8 shrink-0 items-center justify-center rounded-full bg-elevated"><UIcon :name="item.icon" class="size-4 text-primary" /></span><div class="min-w-0 flex-1"><p class="text-sm text-highlighted">{{ item.text }}</p><p class="mt-1 text-xs text-muted">{{ item.time }}</p></div><UBadge color="neutral" variant="subtle">{{ item.source }}</UBadge></div></div></section>
        </section>

        <section v-else-if="activeTab === 'modules'" role="tabpanel"><UCard variant="subtle"><div class="flex items-center justify-between"><div><h2 class="font-semibold text-highlighted">Модули проекта</h2><p class="mt-1 text-sm text-muted">Основные части проекта</p></div><UButton icon="i-lucide-plus" label="Добавить модуль" variant="soft" /></div><div class="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><div v-for="module in project.modules" :key="module" class="flex items-center gap-3 rounded-lg border border-default px-3 py-3"><UIcon name="i-lucide-box" class="size-4 text-primary" /><span class="text-sm text-highlighted">{{ module }}</span></div></div></UCard></section>

        <section v-else-if="activeTab === 'tasks'" role="tabpanel"><UCard variant="subtle"><div class="flex items-center justify-between"><div><h2 class="font-semibold text-highlighted">Задачи из Jira</h2><p class="mt-1 text-sm text-muted">Задачи синхронизируются с Jira, а редактирование открывается там</p></div><UButton icon="i-lucide-refresh-cw" label="Синхронизировать" variant="soft" /></div><div class="mt-5 divide-y divide-default"><div v-for="task in projectTasks" :key="task.key" class="flex items-center justify-between gap-4 py-3 first:pt-0 last:pb-0"><div class="flex items-center gap-3"><span class="font-mono text-xs text-muted">{{ task.key }}</span><p class="text-sm font-medium text-highlighted">{{ task.title }}</p></div><div class="hidden items-center gap-3 sm:flex"><span class="text-xs text-muted">{{ task.status }}</span><UBadge color="neutral" variant="subtle">{{ task.priority }}</UBadge><UAvatar :text="task.assignee" size="xs" color="neutral" /></div></div></div></UCard></section>

        <section v-else-if="activeTab === 'releases'" role="tabpanel"><UCard variant="subtle"><div class="flex items-center justify-between"><div><h2 class="font-semibold text-highlighted">Релизы</h2><p class="mt-1 text-sm text-muted">Состав релиза формируется из задач Jira</p></div><UButton icon="i-lucide-plus" label="Новый релиз" variant="soft" /></div><div class="mt-5 divide-y divide-default"><div v-for="release in releases" :key="release.version" class="flex items-center justify-between gap-4 py-4 first:pt-0 last:pb-0"><div class="flex items-center gap-3"><span class="flex size-9 items-center justify-center rounded-lg bg-elevated"><UIcon name="i-lucide-rocket" class="size-4 text-primary" /></span><div><p class="text-sm font-medium text-highlighted">Версия {{ release.version }}</p><p class="mt-1 text-xs text-muted">{{ release.scope }} · {{ release.date }}</p></div></div><UBadge :color="release.status === 'Выпущен' ? 'success' : 'warning'" variant="subtle">{{ release.status }}</UBadge></div></div></UCard></section>

        <section v-else-if="activeTab === 'environments'" role="tabpanel"><UCard variant="subtle"><div class="flex items-center justify-between"><div><h2 class="font-semibold text-highlighted">Среды проекта</h2><p class="mt-1 text-sm text-muted">Окружения и точки доступа</p></div><UButton icon="i-lucide-plus" label="Добавить среду" variant="soft" /></div><div class="mt-5 flex flex-col gap-3"><div v-for="environment in project.environments" :key="environment.name" class="flex items-center justify-between gap-4 rounded-lg border border-default px-4 py-3"><div class="flex items-center gap-3"><span class="size-2 rounded-full bg-success" /><div><p class="text-sm font-medium text-highlighted">{{ environment.name }}</p><p class="mt-1 text-xs text-muted">{{ environment.detail }}</p></div></div><span class="text-xs text-muted">{{ environment.status }}</span></div></div></UCard></section>

        <section v-else role="tabpanel"><UCard variant="subtle"><div class="flex items-center justify-between"><div><h2 class="font-semibold text-highlighted">Артефакты проекта</h2><p class="mt-1 text-sm text-muted">Ссылки на документацию, макеты и контракты</p></div><UButton icon="i-lucide-plus" label="Добавить ссылку" variant="soft" /></div><div class="mt-5 divide-y divide-default"><a v-for="artifact in project.artifacts" :key="artifact.name" href="#" class="flex items-center justify-between gap-4 py-3 first:pt-0 last:pb-0"><div class="flex items-center gap-3"><div class="flex size-9 items-center justify-center rounded-lg bg-elevated"><UIcon name="i-lucide-link-2" class="size-4 text-primary" /></div><div><p class="text-sm font-medium text-highlighted">{{ artifact.name }}</p><p class="mt-1 text-xs text-muted">{{ artifact.type }} · {{ artifact.url }}</p></div></div><UIcon name="i-lucide-arrow-up-right" class="size-4 text-muted" /></a></div></UCard></section>
      </div>
    </template>
  </UDashboardPanel>
</template>
